spring:
  application:
    name: azure

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://113.198.238.119:3308/azure
    username: azure
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 update, 운영은 validate 권장
    show-sql: true
