spring.application.name=azure

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080

# ==== AGORA (?? + Cloud Recording)
agora.app-id=YOUR_AGORA_APP_ID
agora.app-certificate=YOUR_AGORA_APP_CERT
agora.customer-id=YOUR_AGORA_CUSTOMER_ID
agora.customer-secret=YOUR_AGORA_CUSTOMER_SECRET

# Cloud Recording ?? ??(S3 ?)
agora.bucket.vendor=1
agora.bucket.region=ap-northeast-2
agora.bucket.bucket=your-recording-bucket
agora.bucket.access-key=YOUR_S3_ACCESS_KEY
agora.bucket.secret-key=YOUR_S3_SECRET_KEY
# ??????? {eventId} ?? (Spring ${} ?? ??)
agora.bucket.file-prefix=recordings/event-{eventId}

# ???? ?? ??? ?? URL ???(S3 ??/CloudFront ?)
agora.public-base-url=https://your-bucket.s3.ap-northeast-2.amazonaws.com

# ==== CLOVA Speech (? ?? ??)
clova.endpoint=https://clovaspeech-gw.ncloud.com/external/v1/long
clova.key-id=YOUR_NCP_KEY_ID
clova.key-secret=YOUR_NCP_SECRET
clova.callback-url=https://YOUR-DOMAIN/api/transcripts/callback

spring.datasource.url=jdbc:mysql://113.198.238.119:3308/azure?serverTimezone=Asia/Seoul
spring.datasource.username=azure
spring.datasource.password=1234

# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false



documents.retain-versions=3


spring.task.scheduling.pool.size=2
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.main.allow-bean-definition-overriding=true

storage.base-dir=/var/azure/uploads
